# Generated by Django 6.0.1 on 2026-01-19 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DeptNo', models.IntegerField(primary_key=True, serialize=False)),
                ('Dname', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmpId', models.IntegerField(primary_key=True, serialize=False)),
                ('Ename', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=6)),
                ('Dob', models.DateField()),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Salary', models.FloatField()),
                ('Address', models.CharField(max_length=200)),
                ('DeptNo', models.ForeignKey(db_column='DeptNo', on_delete=django.db.models.deletion.CASCADE, to='App.department')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
